### ISSUE TITLE
Floating point precision sensitivity in tri_line_intersect

### ISSUE THREAD

**Issue by WazWaz** [BorisTheBrave/grids#2] opened 2023-02-27 02:18 UTC
It seems tri_line_intersect has a floating point sensitivity. For example,

   tri_line(2,-8,7, 23,-27,6)

returns only about half the line:

(2, -8, 7)
(3, -8, 7)
(3, -9, 7)
(4, -9, 7)
(4, -10, 7)
(5, -10, 7)
(5, -11, 7)
(6, -11, 7)
(6, -12, 7)
(7, -12, 7)
(7, -13, 7)
(8, -13, 7)
(8, -14, 7)
(9, -14, 7)
(9, -15, 7)
(10, -15, 7)
(10, -16, 7)
(11, -16, 7)
(11, -17, 7)
(12, -17, 7)
(12, -17, 6)

Clearly this should end at (23,-27,6) rather than (12, -17, 6).

Debugging showed ta and tb being extremely close to equal, so as a test, I added an epsilon to the RHS of the <= checks in the loop. This seems to fix the problem in my limited testing, but I didn't completely understand the cause. It doesn't appear to be sensitive to edge_length.

I'm actually working with my C# port of your code, but I've confirmed the problem also exists in the python original. But it's why I must apologize for not presenting this as a failed test case. The test would be to ensure that a large number of pairs in a grid reach the end of the line.

**Comment by BorisTheBrave** [comment] 2023-03-24 10:59
Sorry, I missed this issue. I'll take a look soon.

In the meantime, have you seen Sylves, my newer C# library for grids. It may cover your use case better?

https://github.com/BorisTheBrave/sylves

**Comment by BorisTheBrave** [comment] 2023-03-25 09:07
Fixed in https://github.com/BorisTheBrave/grids/commit/94137be706f888151430d645cf990dc6e76465d3

The issue is that when lines go through the corner of a triangle, it crosses several boundaries at once. Due to precision issues, it can sometimes cross the boundaries in an invalid order. I've improved the logic to handle this.

**Closed as completed by BorisTheBrave** 2023-03-25 09:07 UTC
